apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadbtest0
spec:
  storageClassName: mystorageclass0
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/haproxy/data/mysql/mariadb-test0"
    server: "192.168.1.48"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadbtest1
spec:
  storageClassName: mystorageclass1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/haproxy/data/mysql/mariadb-test1"
    server: "192.168.1.48"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadbtest2
spec:
  storageClassName: mystorageclass2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/haproxy/data/mysql/mariadb-test2"
    server: "192.168.1.48"
